### ISSUE TITLE
Upgrading to Assemble 0.6.0

### ISSUE THREAD

**Issue by briantjacobs** [assemble/grunt-assemble#12]
When installing this via npm I managed to miss the "not ready for use" bit. Oops. But now that it's installed, working great my Grunt setup, Assemble 0.6.0 looks useful. Can you recommend a way I could update Assemble to that version before I try something irresponsible?

**Comment by jonschlinkert** [comment]
Upgrade the grunt plugin to work with Assemble v0.6.0? We haven't even begun work on that yet. My recommendation would be to use v0.6.0 directly (without grunt or gulp). It's much more powerful

**Comment by briantjacobs** [comment]
Cool. In that case I'll just stick with the version of Assemble in the grunt-assemble plugin, as the grunt integration is pretty important for me right now. Thanks for the reply.

**Comment by jonschlinkert** [comment]
> as the grunt integration is pretty important for me right now. Thanks for the reply.

yeah, no problem. we do plan to update the plugin. we'll updated this when we do

**Comment by brunowego** [comment]
+1

**Comment by amazingSurge** [comment]
Waiting for this update. thanks in advance.

**Comment by andrexbass** [comment]
+1

**Comment by tiagovtg** [comment]
+1

**Comment by DenisMir** [comment]
Waiting for the grunt plugin as well.

**Comment by floriangosse** [comment]
We use grunt for our complex build process and want to use it in the future too. Is a branch available where the integration for assemble 0.6.0 is developed?

**Comment by jonschlinkert** [comment]
no, but @doowb and I have been talking a lot about this lately. we both want to get this implemented be we've been crunched on time lately so we're trying to stay focused on assemble and docs

**Comment by jonschlinkert** [comment]
actually, I just remembered I started working on this a couple weeks ago, I might be able to finish it up quickly. I'll report back when I have a chance to look. feel free to ping me if you don't hear from me for a couple days!

**Comment by gunnx** [comment]
Is that "not ready for use" comment still valid? People seem to be using /assemble/grunt-assemble instead of assemble/assemble. I would like to use assemble with handlebars 3.x, is this the best version to use or install assemble0.6 instead.

**Comment by DenisMir** [comment]
@gunnx Start using grunt-assemble. You will get version 4.x of assemble but with handlebars 3.x support.

**Comment by bjankord** [comment]
I'm running into this [exact issue](https://github.com/assemble/assemble/issues/781). It has been marked as fixed in 0.6.0 so I'm looking forward to grunt-assemble getting updated.

**Comment by jonschlinkert** [comment]
Closing since this isn't really an issue and based on age. If you have handlebars, or grunt-assemble related issues, it's best to discuss those on the grunt-assemble repo or handlebars-helpers, or the repo that is most related.

**Comment by jonschlinkert** [comment]
.. unless it is related to grunt-assemble, in which case we should create a new issue for it
