### ISSUE TITLE
Loading "assemble.js" tasks...ERROR >> Error: Cannot find module 'grunt'

### ISSUE THREAD

**Issue by foxx** [assemble/grunt-assemble#13]
Possibly related to a similar issue seen [here][1]. 

```
$ grunt -d -v --stack
Loading "assemble.js" tasks...ERROR
>> Error: Cannot find module 'grunt'
>>     at Function.Module._resolveFilename (module.js:336:15)
>>     at Function.Module._load (module.js:278:25)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at Object.<anonymous> (/tmp/tmp.I0luo8CrFI/grunt-assemble/lib/utils.js:10:13)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
```

It seems to be that you are doing the following;

```
util.js
var grunt = require('grunt');
```

However every other module I've seen does not do this, instead they use tasks with a variable passed in, as seen in their official [docs][2].

Here are my versions;

```
npm=2.7.4
nvm=0.25.0
node=v0.12.2
grunt-assemble 0.2.0
grunt-cli v0.1.13
grunt v0.4.5
```

[1]: https://github.com/jmreidy/grunt-browserify/issues/325
[2]: https://github.com/gruntjs/grunt-init-gruntplugin

**Comment by foxx** [comment]
It would seem this problem is being caused by `grunt-assemble` being completely unsupported and not ready for use yet. This is unclear, apart from a small obscure bit of text in the description. Can you please add a BIG WARNING onto the README that states this is not ready for use yet. The existing warning means nothing.

**Comment by doowb** [comment]
@foxx `grunt-assemble@0.2.0` is the same code as `assemble@0.4.42`. We pulled it over in an attempt to follow the `grunt-*` pattern for grunt plugins. `assemble@0.6.0` is completely detached from grunt, but is still only published as beta on npm.

The description needs to be updated since that was intended for `grunt-assemble < 0.2.0` when we were trying to wrap the new version of assemble.

With that being said... will you try `assemble@0.4.42` (remember to update `grunt.loadNpmTasks` in your Gruntfile.js) to see if you're getting the same error. If you are, will you post your `package.json` and `Gruntfile.js` or at least a sample repo showing the failure?

**Comment by foxx** [comment]
Thanks for the quick reply, I can confirm that I'm still getting the problem;

Gruntfile.js:
```
module.exports = function (grunt) {
  grunt.loadNpmTasks('grunt-assemble'); 
}
```

I also tried;

```
grunt.loadNpmTasks('assemble');
```

Both result in;

```
Loading "assemble.js" tasks...ERROR
>> Error: Cannot find module 'grunt'
>>     at Function.Module._resolveFilename (module.js:336:15)
>>     at Function.Module._load (module.js:278:25)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at Object.<anonymous> (/tmp/tmp.jqnxMwsqeO/assemble/lib/utils.js:10:13)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
```

package.json
```
{
  "name": "XXXX",
  "version": "1.0.0",
  "description": "XXXX",
  "author": {
    "name": "Cal Leeming",
    "email": "cal@iops.io",
    "url": "iops.io"
  },
  "repository": "XXXX",
  "dependencies": {},
  "devDependencies": {
    "assemble": "^0.4.42",
    "assemble-swig": "^0.1.0",
    "bower": "^1.4.1",
    "connect-livereload": "^0.5.3",
    "express": "^4.12.3",
    "grunt": "^0.4.5",
    "grunt-browserify": "^3.7.0",
    "grunt-cli": "^0.1.13",
    "grunt-concurrent": "^1.0.0",
    "grunt-contrib-compass": "^1.0.3",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-express-server": "^0.5.1",
    "jquery": "^2.1.3",
    "load-grunt-tasks": "^3.1.0",
    "swig": "^1.4.2"
  }
}
```

**Comment by jonschlinkert** [comment]
> Cannot find module 'grunt'

Did you read the error messages?

**Comment by jonschlinkert** [comment]
> Can you please add a BIG WARNING onto the README that states this is not ready for use yet. The existing warning means nothing.

we can add one that says you're not read to use it if you want. but the other 490,000 users haven't created this issue.

**Comment by foxx** [comment]
Yes I did read the error message, but grunt is installed and there. I don't understand why you have given a sarcastic response tbh.

**Comment by jonschlinkert** [comment]
because you were rude and hyperbolistic in your message

**Comment by jonschlinkert** [comment]
want better support, be nice
