### ISSUE TITLE
Completely uncalled for

### ISSUE THREAD

**Issue by foxx** [assemble/grunt-assemble#14]
Follow up from [here][1].

Nice passive agressive approach of blocking the thread. I'm not asking for support, I was trying to raise a bug report so other users didn't have to deal with this problem in the future. I don't know what your deal is, but this is still a valid bug. Either way, I'm giving up on this library, but seriously, this isn't how you maintain an open source project. You should fix this problem for other users either way.

[1]: https://github.com/assemble/grunt-assemble/issues/13#issuecomment-97124043

**Comment by jonschlinkert** [comment]
please stop making rude comments on the assemble issues
