### ISSUE TITLE
Custom delimeters for gray matter

### ISSUE THREAD

**Issue by MarkySparky** [assemble/grunt-assemble#16]
Custom YAML delimeter in a task?

Something like...
```js
 md: {
        // Target-level options
        options: {
            layout: 'org-hub.hbs',
            yaml: {
                delim: '~~~'
            },
            marked: {
                sanitize: false,
                gfm: true,
                tables: true,
                breaks: false
            }
        },
        files: [{
            expand: true,
            cwd: '<%= site.contentitems %>',
            src: ['articlemarkdown/**/*.yaml'],
            dest: '<%= site.pages %>'
        }]
    }
```

I see that gray-matter supports this, but I cant find a way to pass these options through using griunt-assemble.

Many thanks
Mark

**Comment by jonschlinkert** [comment]
there are three places where gray-matter is called, we'll need to allow an options argument to be passed to each:

- https://github.com/assemble/grunt-assemble/blob/05005ed6975bcc9f3b4476b0e9beeb82eb5d14c5/tasks/assemble.js#L121
- https://github.com/assemble/grunt-assemble/blob/05005ed6975bcc9f3b4476b0e9beeb82eb5d14c5/tasks/assemble.js#L283
- https://github.com/assemble/grunt-assemble/blob/05005ed6975bcc9f3b4476b0e9beeb82eb5d14c5/tasks/assemble.js#L655
