### ISSUE TITLE
handlebars

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/grunt-assemble#18]
Just wanted to cross-link this issue in case anyone has handlebars problems. https://github.com/assemble/assemble-handlebars/issues/29#issuecomment-101480822.

In a nutshell:
- use `grunt-assemble` in your gruntfile, not `assemble`
- make sure you have the latest version. 

sorry for any confusion!

**Comment by doowb** [comment]
Sounds like this was resolved, I'm going to close but please feel free to reopen or create a new issue if:
- the bug is still happening
- you're still having problems
