### ISSUE TITLE
can partials decouple data from view

### ISSUE THREAD

**Issue by partnuz** [assemble/grunt-assemble#24]
First of all thank you for your work. I have a question. Let's say we have this code in list.hbs

    <ul>
    {{#each data }}
     <li class="{{class}}">{{content}}</li>
    {{\each}}
    </ul>

I want to use it somewhere else using this code

    {{#each concrete_data }}
    {{>list}}
    {{\each}}

Is this possible ?

**Comment by jonschlinkert** [comment]
absolutely. this is handlebars syntax though, so you'll want to read up on scope and how context works in  blocks/loops. http://handlebarsjs.com/
