### ISSUE TITLE
grunt-assemble + grunt-webpack = lost plugin definition in webpack configuration

### ISSUE THREAD

**Issue by StephanGerbeth** [assemble/grunt-assemble#27]
Hi,

i have a strange bug when i run grunt-assemble and grunt-webpack in the same task.

I try to explain it:
- I registered an own task by `grunt.registerTask('build', ['assemble', 'webpack']);`
- the task abort with the following message `Running "webpack:app" (webpack) task
Warning: arguments[i].apply is not a function Use --force to continue.`
- At first i thought: "Uh there is bug in webpack, i try to fix it!". I analyzed the code and i found a hint [here](https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L62). 
- `options.plugins` has empty objects inside. Usually some plugins should be listed which i defined inside the webpack configuration e.g. dedupe, polyfills, uglify.
- For any reason i changed the order inside my grunt task to `grunt.registerTask('build', ['webpack', 'assemble']);`
- AND - the complete task is running successfull :) 
- But it is really important for me to run assemble at first. So this solution is useless for me. :(

My conclusion:
I think a bug is inside assemble which modifies the plugin definition of other tasks. But i'm not sure, because i can't locate him.

Can you help me to solve this strange one?

This is my repo to reproduce the problem: [Link](https://github.com/StephanGerbeth/boilerplate)
Run `grunt build`

Cheers
Stephan

**Comment by StephanGerbeth** [comment]
UPDATE:
I can isolate the bug inside the aggregate helper.
if i remove this helper inside my project everything works fine.
Should i move this issue to the helper-aggregate git repo?

**Comment by jonschlinkert** [comment]
> Should i move this issue to the helper-aggregate git repo?

Yes, that would be great. thanks. closing here
