### ISSUE TITLE
feature request: Jade templates

### ISSUE THREAD

**Issue by adamwong246** [assemble/grunt-assemble#8]
Handlebars are great and all, I guess but I'd rather just plop some js down in my templates  rather than deal with the overhead of handlebars helpers. Is handlebars welded into assemble or is there room for other engines?

**Comment by brunowego** [comment]
+1

**Comment by jonschlinkert** [comment]
closing in light of the pending release of assemble v0.6.0. 

here's how to register an engine in v0.6.0:

```js
var assemble = require('assemble');
var cons = require('consolidate');
assemble.engine('jade', cons.jade);
```
