### ISSUE TITLE
Module not found problem

### ISSUE THREAD

**Issue by ijdickinson** [assemble/grunt-assemble#9]
I'm trying to run a Gruntfile that I got working on one machine on another (very similar) machine, but getting a 'module not found' problem in the grunt-assemble task. I don't know that this is an issue with grunt-assemble per se, but any insights you might have would be very welcome.

Rather than duplicate the problem description here, here's a [link to the StackOverflow write-up](http://stackoverflow.com/questions/27229719/grunt-assemble-strange-module-not-found-issue)

**Comment by doowb** [comment]
This issue should be resolved with the latest `grunt-assemble`. If not, please reopen.
